version: '3'

services:
  database:
    build:
      context: ./database
    container_name: db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: ebariquello
      MYSQL_PASSWORD: pass@word1
      MYSQL_ROOT: sa
      MYSQL_ROOT_PASSWORD: pass@word1
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql  
    networks: 
      - app-network
  nginx:
    build:
      context: ./nginx
    container_name: webserver  
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm        
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - app-network
  php-fpm:
    build:    
      context: ./php-fpm
    container_name: app 
    volumes:
      - ../src:/var/www 
    networks: 
      - app-network  


networks:
  app-network:
    driver: bridge
